config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/donations', as: :user_donation

  get 'static_pages/volunteer', as: :user_volunteer

  resources :animal_images
  get 'employees/list' => 'employees#list', as: :employees_list
  devise_for :employees, controllers: {sessions: "sessions", registrations: "employees"}
  resources :employees do
    collection do
      get 'animals' => 'animals#list', as: :animals_list
      get 'animals/new' => 'animals#new', as: :new_animal
      get 'animals/:id' => 'animals#show_employees', as: :show_animal
    end
  end
  get 'dogs' => 'animals#list_dogs', as: :animals_dogs
  get 'cats' => 'animals#list_cats', as: :animals_cats
  get 'animals/filters' => 'animals#filters', as: :animal_filters
  post  'requests/all'  =>            'requests#update_all', as: :update_all_request
  post  'requests/:id'  =>            'requests#update', as: :update_request
  get 'return_animal/:id' => 'animals#return', as: :return_animal_to_shelter
  get 'requests/new/:animal_id' => 'requests#new', as: :new_adoption_request

  get 'endanger/:id' => 'animals#endanger', as: :animal_in_danger
  get 'save/:id' => 'animals#save', as: :animal_save

  delete 'requests' => 'requests#destroy_all'
  get 'global_stats' => 'charts#global_stats', as: :global_stats
  get 'donations_stats' => 'donations#stats', as: :donations_stats

  resources :animals
  resources :requests, only: [:index, :new, :create,:destroy]
  resources :adoptions
  resources :shelter
  resources :donations
  resources :volunteers
  resources :emails, only: [:new, :create]

  get '/'                        => 'static_pages#index',         as: :user_index
  get '/about'                   => 'static_pages#about',         as: :about
  get '/contacts'                => 'static_pages#contacts',      as: :contacts
  get '/animals'                 => 'animals#user_index',         as: :animals_user_index

   root 'static_pages#index'

   match "*path" => "static_pages#index", via: [:get, :post]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout "users"
  def index
  end

  def about
    @shelter = Shelter.first
  end

  def contacts
    @email = Email.new
    @shelter = Shelter.first
  end

  def donations
  end

  def volunteer
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contacts.html.erb
<section class="page-content">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
          <br>
        <div class="box-style-grey">
          <h2 class="text-style-grey" align="center"><%=@shelter.name %></h2>
          <hr>
          <p class="text-justify">
            <strong> Our goal:</strong> <%=@shelter.description %>
          </p>
          <p class="text-justify"><strong> Foundation:</strong> Our institution was founded in <%=@shelter.opening_date %></p>
          <p class="text-justify">Since then we've been working to get help to thousands of animals, but we can't make it alone!</p>
          <p class="text-justify">Everyone is welcome to join us in our battle, come meet us!</p>
        </div>
        <br>
        <div class="col-md-12">
          <hr class="visible-sm visible-xs lg">
          <!-- Widget :: Contacts Info -->
          <div class="contacts-widget widget widget__sidebar">
            <div class="widget-content">
              <ul class="contacts-info-list">
                <br>
                <li>
                  <i class="fa fa-map-marker fa-2x"></i>
                  <div class="info-item">
                    <%=@shelter.address%>
                <li>
                  <i class="fa fa-envelope"></i>
											<span class="info-item">
												<a href="mailto:info@dan-fisher.com">
                          <%=@shelter.email%> </a>
											</span>
                </li>
                <li>
                  <i class="fa fa-phone"></i>
											<span class="info-item">
                          <%=@shelter.phone%>
											</span>
                </li>
                <li>
                  <i class="fa fa-clock-o"></i>
                  <div class="info-item">
                    <%=@shelter.schedule%>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

        <div class="col-md-6">
        <div class="googlemap-wrapper">
          <div id="map_canvas" class="map-canvas"></div>

          <script>
            var map;
            function initMap() {

              map = new google.maps.Map(document.getElementById('map_canvas'), {
                center: {lat: 40.2033145, lng: -8.410257300000012},
                zoom: 7
              });
              var marker;
              var infowindow = new google.maps.InfoWindow();
              marker = new google.maps.Marker({
                position: {
                  lat:<%= Geocoder.search(@shelter.address)[0].latitude%>,
                  lng: <%=Geocoder.search(@shelter.address)[0].longitude%>
                },
                map: map,
                title: '<%=@shelter.name%>'
              });


              google.maps.event.addListener(marker, 'click', (function (marker) {
                return function () {
                  infowindow.setContent('<%=@shelter.name%>' + ', ' + '<%=@shelter.address%>');
                  infowindow.open(map, marker);
                }
              })(marker));


            }
          </script>
        </div>

      </div>

    </div>

          <div class="row">
            <div class="col-md-12">
              <hr>
              <h2>Contact Form</h2>
              <%= form_for @email,validate: true  do |f| %>


                  <form  id="contact-form">
                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label><%= f.label :name %> <span class="required">*</span></label>
                          <%= f.text_field :name,:required => true,
                                           placeholder: "Please enter your name.",
                                           class: "form-control" %>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label><%= f.label :email_from %> <span class="required">*</span></label>
                          <%= f.email_field :email_from, :required => true,
                                            placeholder: "Please enter a valid email address.",
                                            class: "form-control" %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label><%= f.label :text_message %> <span class="required">*</span></label>

                          <%= f.text_area :text_message, as: :text, :required => true,
                                          placeholder: "Please enter your message.",
                                          class: "form-control" , rows: "10"%>
                        </div>
                      </div>
                    </div>


                    <div class="hidden">
                      <%= f.label :nickname %>
                      <%= f.text_field :nickname, hint: 'leave this field blank' %>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <%= f.submit 'Send Message', class: 'btn btn-primary' %>
                      </div>
                    </div>
              <% end %>
              </form>

              </div>
          </div>
  </div>


</section>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_H6CJwxGOMchdb5VUD32Xfr7pZoZVZ5s&callback=initMap"
        async defer></script>

app/views/static_pages/donations.html.erb
<div class="container">
  <h2 class="page-header">Donations <%= image_tag '/assets/images/icon1.png' %></h2>
  <div class="row">
    <div class="col-md-6">
      <div class="box-style-green">
        <h4 class="text-style-green"> Why Donate?</h4>
        <p>Our institution relies directly on the help of good people to maintain our doors open! We need your help to continue our work and help the animals in need!
      </div>
      <br>
      <div class="box-style-orange">
        <h4 class="text-style-orange"> What Can I Donate?</h4>
        <p>Almost everything is permitted, you can donate toys, clothes or accessories, food, money. Whatever you have that an animal could use it's safe to donate.</p>
      </div>

      <br>

      <div class="box-style-blue">
        <h4 class="text-style-blue"> How to Donate?</h4>
        <p>You can go directly to our shelter and make your donation or you can fill in a request here and wait for someone to contact you, just click the button below.</p>
      </div>

      <div class="row">
        <div class="col-md-2 col-md-offset-4">
          <br>
          <%= button_to 'Donation Request', new_request_path , class:'btn btn-large btn-primary', method:'get'%>
          <br>
        </div>

      </div>

    </div>
    <%= image_tag '/assets/images/donation-image-page.png' , class: 'img-responsive'%>




  </div>
</div>

</div>

app/views/static_pages/index.html.erb
<!-- Carousel
    ================================================== -->
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag '/assets/images/adoption_image.jpg'%>
      <div class="container">
        <div class="carousel-caption">
          <h1>They need <i>YOU</i></h1>
          <p class="lead">It's easy to make them happy</p>
          <%= button_to 'Adopt a friend', animals_path , class:'btn btn-large btn-primary', method:'get'%>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag '/assets/images/donation_image.png'%>
      <div class="container">
        <div class="carousel-caption">
          <h1>Our cause</h1>
          <p class="lead">Is their <i>happiness</i></p>
          <%= button_to 'Donate now', user_donation_path , class:'btn btn-large btn-primary', method:'get'%>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag '/assets/images/volunteer_image.jpg'%>
      <div class="container">
        <div class="carousel-caption">
          <h1>They need your <strong>Love</strong>!</h1>
          <p class="lead">Help us today</p>
          <%= button_to 'Volunteer', user_volunteer_path , class:'btn btn-large btn-primary', method:'get'%>
        </div>
      </div>
    </div>
    </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
</div><!-- /.carousel -->

<!-- Marketing messaging and featurettes
    ================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing fix-12-col">

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="span4">
      <%= link_to image_tag('/assets/images/images_adopt.jpg', class:'img-circle', alt:'Adopt a friend', width: '140px', height: '140px', onmouseover: "this.src='/assets/images/images_adopt_color.png'", onmouseout: "this.src='/assets/images/images_adopt.jpg'") , animals_path%>
      <h2>Adoptions</h2>
      <p>Every year thousands of dogs are abandoned by their owners, they don't know why that person, who they love most of all, is leaving them. They find themselves alone without food or care. We try to help all of them but it is impossible! Help us take care of an innocent soul! Our shelter is open 24/7 for adoptions, come visit! </p>
      <p><%= button_to 'Adopt', animals_path , class:'btn btn-large btn-primary', method:'get'%></p>
    </div><!-- /.span4 -->
    <div class="span4">
      <%= link_to image_tag('/assets/images/images_donation.jpg', class:'img-circle', alt:'Donate now', width: '140px', height: '140px', onmouseover: "this.src='/assets/images/donations-circle-red.png'", onmouseout: "this.src='/assets/images/images_donation.jpg'"), user_donation_path%>
      <h2>Donations</h2>
        <p>These pets need all the help they can get. They are thousands so it's really hard to get the funds to give them a decent life. We aim to provide the best conditions for every single one, for that we need some help! They deserve our effort, find out how you can help or donate to our cause. </p>
      <p><%= button_to 'Donate', user_donation_path , class:'btn btn-large btn-primary', method:'get'%></p>
    </div><!-- /.span4 -->
    <div class="span4">
      <%= link_to image_tag('/assets/images/images_volunteer.png', class:'img-circle', alt:'Donate now', width: '140px', height: '140px', onmouseover: "this.src='/assets/images/images_volunteer_color.png'", onmouseout: "this.src='/assets/images/images_volunteer.png'"), user_volunteer_path %>
      <h2>Volunteering</h2>
        <p>Our pets want nothing but to show the love they have for us. Unfortunatly we can't be with them all the time, so we rely on our volunteers to help us fullfill the needs of these beautiful creatures. Be part of the solution for them. You can apply here to work with us at your own schedule.</p>
      <p><%= button_to 'Volunteer', user_volunteer_path , class:'btn btn-large btn-primary', method:'get'%></p></p>
    </div><!-- /.span4 -->
  </div><!-- /.row -->

</div>

app/views/static_pages/volunteer.html.erb
<div class="container">
  <h2 class="page-header">Working With Us <%= image_tag '/assets/images/icon1.png' %></h2>
<div class="row">
    <div class="col-md-6">
      <div class="box-style-green">
      <h4 class="text-style-green"> Why Volunteer?</h4>
        <p>Our institution relies directly on the help of good people to maintain our doors open! We need your help to continue our work and help the animals in need!
        </div>
      <br>
      <div class="box-style-orange">
      <h4 class="text-style-orange"> Volunteer Work</h4>
          <p>There are many ways to help us in our cause: walk the dogs, bathe them, gather donations and so on. We aim to find something that suits everyone!</p>
    </div>

      <br>

      <div class="box-style-blue">
        <h4 class="text-style-blue"> How to Become a Volunteer?</h4>
            <p>You can go directly to our shelter and volunteer or you can fill in a request here and wait for someone to contact you, just click the button below.</p>
      </div>

      <div class="row">
        <div class="col-md-2 col-md-offset-4">
          <br>
          <%= button_to 'Volunteer Request', new_request_path , class:'btn btn-large btn-primary', method:'get'%>
          <br>
        </div>

      </div>

    </div>
          <%= image_tag '/assets/images/shelter_volunteer.jpg' , class: 'img-responsive'%>




  </div>
</div>