config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/donations', as: :user_donation

  get 'static_pages/volunteer', as: :user_volunteer

  resources :animal_images
  get 'employees/list' => 'employees#list', as: :employees_list
  devise_for :employees, controllers: {sessions: "sessions", registrations: "employees"}
  resources :employees do
    collection do
      get 'animals' => 'animals#list', as: :animals_list
      get 'animals/new' => 'animals#new', as: :new_animal
      get 'animals/:id' => 'animals#show_employees', as: :show_animal
    end
  end
  get 'dogs' => 'animals#list_dogs', as: :animals_dogs
  get 'cats' => 'animals#list_cats', as: :animals_cats
  get 'animals/filters' => 'animals#filters', as: :animal_filters
  post  'requests/all'  =>            'requests#update_all', as: :update_all_request
  post  'requests/:id'  =>            'requests#update', as: :update_request
  get 'return_animal/:id' => 'animals#return', as: :return_animal_to_shelter
  get 'requests/new/:animal_id' => 'requests#new', as: :new_adoption_request

  get 'endanger/:id' => 'animals#endanger', as: :animal_in_danger
  get 'save/:id' => 'animals#save', as: :animal_save

  delete 'requests' => 'requests#destroy_all'
  get 'global_stats' => 'charts#global_stats', as: :global_stats
  get 'donations_stats' => 'donations#stats', as: :donations_stats

  resources :animals
  resources :requests, only: [:index, :new, :create,:destroy]
  resources :adoptions
  resources :shelter
  resources :donations
  resources :volunteers
  resources :emails, only: [:new, :create]

  get '/'                        => 'static_pages#index',         as: :user_index
  get '/about'                   => 'static_pages#about',         as: :about
  get '/contacts'                => 'static_pages#contacts',      as: :contacts
  get '/animals'                 => 'animals#user_index',         as: :animals_user_index

   root 'static_pages#index'

   match "*path" => "static_pages#index", via: [:get, :post]

end

app/models/animal_image.rb
class AnimalImage < ActiveRecord::Base
  mount_uploader :image, AnimalImageUploader
  belongs_to :animal
end

app/controllers/animal_images_controller.rb
class AnimalImagesController < ApplicationController
  before_action :set_animal_image, only: [:show, :edit, :update, :destroy]
  before_filter :custom_user_auth, only: [:edit, :update, :destroy]

  # GET /animal_images
  # GET /animal_images.json
  def index
    @animal_images = AnimalImage.all
  end

  # GET /animal_images/1
  # GET /animal_images/1.json
  def show
  end

  # GET /animal_images/new
  def new
    @animal_image = AnimalImage.new
  end

  # GET /animal_images/1/edit
  def edit
  end

  # POST /animal_images
  # POST /animal_images.json
  def create
    @animal_image = AnimalImage.new(animal_image_params)

    respond_to do |format|
      if @animal_image.save
        format.html { redirect_to @animal_image, notice: "Animal image was successfully created." }
        format.json { render :show, status: :created, location: @animal_image }
      else
        format.html { render :new }
        format.json { render json: @animal_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animal_images/1
  # PATCH/PUT /animal_images/1.json
  def update
    respond_to do |format|
      if @animal_image.update(animal_image_params)
        format.html { redirect_to @animal_image, notice: "Animal image was successfully updated." }
        format.json { render :show, status: :ok, location: @animal_image }
      else
        format.html { render :edit }
        format.json { render json: @animal_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animal_images/1
  # DELETE /animal_images/1.json
  def destroy
    @animal_image.destroy
    respond_to do |format|
      format.html
      format.js {}
      format.json { render json: { ok: true } }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_animal_image
    @animal_image = AnimalImage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def animal_image_params
    params.require(:animal_image).permit(:animal_id, :image, :remove_image)
  end
end

app/helpers/animal_images_helper.rb
module AnimalImagesHelper
end

app/views/animal_images/_form.html.erb
<%= form_for(@animal_image) do |f| %>
  <% if @animal_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal_image.errors.count, "error") %> prohibited this animal_image from being saved:</h2>

      <ul>
      <% @animal_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :animal_id %><br>
    <%= f.number_field :animal_id %>
  </div>
  <div class="field">
    <%= f.label :images %><br>
    <%= f.text_area :images %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animal_images/edit.html.erb
<h1>Editing Animal Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal_image %> |
<%= link_to 'Back', animal_images_path %>

app/views/animal_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Animal Images</h1>

<table>
  <thead>
    <tr>
      <th>Animal</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animal_images.each do |animal_image| %>
      <tr>
        <td><%= animal_image.animal_id %></td>
        <td><%= animal_image.images %></td>
        <td><%= link_to 'Show', animal_image %></td>
        <td><%= link_to 'Edit', edit_animal_image_path(animal_image) %></td>
        <td><%= link_to 'Destroy', animal_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal image', new_animal_image_path %>

app/views/animal_images/new.html.erb
<h1>New Animal Image</h1>

<%= render 'form' %>

<%= link_to 'Back', animal_images_path %>

app/views/animal_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Animal:</strong>
  <%= @animal_image.animal_id %>
</p>

<p>
  <strong>Images:</strong>
  <%= @animal_image.images %>
</p>

<%= link_to 'Edit', edit_animal_image_path(@animal_image) %> |
<%= link_to 'Back', animal_images_path %>