config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/donations', as: :user_donation

  get 'static_pages/volunteer', as: :user_volunteer

  resources :animal_images
  get 'employees/list' => 'employees#list', as: :employees_list
  devise_for :employees, controllers: {sessions: "sessions", registrations: "employees"}
  resources :employees do
    collection do
      get 'animals' => 'animals#list', as: :animals_list
      get 'animals/new' => 'animals#new', as: :new_animal
      get 'animals/:id' => 'animals#show_employees', as: :show_animal
    end
  end
  get 'dogs' => 'animals#list_dogs', as: :animals_dogs
  get 'cats' => 'animals#list_cats', as: :animals_cats
  get 'animals/filters' => 'animals#filters', as: :animal_filters
  post  'requests/all'  =>            'requests#update_all', as: :update_all_request
  post  'requests/:id'  =>            'requests#update', as: :update_request
  get 'return_animal/:id' => 'animals#return', as: :return_animal_to_shelter
  get 'requests/new/:animal_id' => 'requests#new', as: :new_adoption_request

  get 'endanger/:id' => 'animals#endanger', as: :animal_in_danger
  get 'save/:id' => 'animals#save', as: :animal_save

  delete 'requests' => 'requests#destroy_all'
  get 'global_stats' => 'charts#global_stats', as: :global_stats
  get 'donations_stats' => 'donations#stats', as: :donations_stats

  resources :animals
  resources :requests, only: [:index, :new, :create,:destroy]
  resources :adoptions
  resources :shelter
  resources :donations
  resources :volunteers
  resources :emails, only: [:new, :create]

  get '/'                        => 'static_pages#index',         as: :user_index
  get '/about'                   => 'static_pages#about',         as: :about
  get '/contacts'                => 'static_pages#contacts',      as: :contacts
  get '/animals'                 => 'animals#user_index',         as: :animals_user_index

   root 'static_pages#index'

   match "*path" => "static_pages#index", via: [:get, :post]

end

app/models/adoption.rb
class Adoption < ActiveRecord::Base
  belongs_to :animal
  belongs_to :user
  belongs_to :employee

  validates_presence_of :user_id, :animal_id, :adoption_date, :adoption_type, :employee_id
  validate :adoption_not_in_future
  validate :user_cc

  def user_cc
    if user_id == ""
      errors.add(:user_id, "cannot be blank")
    end
  end

  def adoption_not_in_future
    unless adoption_date.nil?
      now = DateTime.now.to_date
      if now < adoption_date
        errors.add(:adoption_date, "cannot be in the future")
      end
    end
  end

  scope :last_month_adoptions, -> {
    where("adoption_date >= ? AND adoption_date <= ?",
      Date.today.beginning_of_month.to_date,
      Date.today.end_of_month.to_date)
  }

  def self.amount_1_year_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      1.year.ago.beginning_of_month.to_date,
      1.year.ago.end_of_month.to_date).size
  end

  def self.amount_11_months_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      11.months.ago.beginning_of_month.to_date,
      11.months.ago.end_of_month.to_date).size
  end

  def self.amount_10_months_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      10.months.ago.beginning_of_month.to_date,
      10.months.ago.end_of_month.to_date).size
  end

  def self.amount_9_months_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      9.months.ago.beginning_of_month.to_date,
      9.months.ago.end_of_month.to_date).size
  end

  def self.amount_8_months_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      8.months.ago.beginning_of_month.to_date,
      8.months.ago.end_of_month.to_date).size
  end

  def self.amount_7_months_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      7.months.ago.beginning_of_month.to_date,
      7.months.ago.end_of_month.to_date).size
  end

  def self.amount_6_months_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      6.months.ago.beginning_of_month.to_date,
      6.months.ago.end_of_month.to_date).size
  end

  def self.amount_5_months_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      5.months.ago.beginning_of_month.to_date,
      5.months.ago.end_of_month.to_date).size
  end

  def self.amount_4_months_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      4.months.ago.beginning_of_month.to_date,
      4.months.ago.end_of_month.to_date).size
  end

  def self.amount_3_months_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      3.months.ago.beginning_of_month.to_date,
      3.months.ago.end_of_month.to_date).size
  end

  def self.amount_2_months_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      2.months.ago.beginning_of_month.to_date,
      2.months.ago.end_of_month.to_date).size
  end

  def self.amount_1_month_ago
    Adoption.where("adoption_date >= ? AND adoption_date <= ?",
      1.month.ago.beginning_of_month.to_date,
      1.month.ago.end_of_month.to_date).size
  end
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  before_action :set_adoption, only: [:show, :edit, :update, :destroy]
  before_filter :custom_user_auth
  before_action :set_necessary

  def set_necessary
    @users = User.all
    @animals = Animal.where(status: 0)
  end

  # GET /adoptions
  # GET /adoptions.json
  def index
    @adoptions = Adoption.all
    @permanent_adoptions = Adoption.where(adoption_type: 1)
    @temporary_adoptions = Adoption.where(adoption_type: 2)
  end

  # GET /adoptions/1
  # GET /adoptions/1.json
  def show
    @previous_adoptions = Adoption.where(user_id: @adoption.user.id).where.not(id: @adoption.id)
  end

  # GET /adoptions/new
  def new
    @adoption = Adoption.new
    @animals = Animal.where(status: 0)
    @users = User.all
  end

  # GET /adoptions/1/edit
  def edit
    @animals = Animal.where(status: 0)
    @animals_codes = Animal.all
  end

  # POST /adoptions
  # POST /adoptions.json
  def create
    var = 0
    @user = User.new(cc: 111111, name: "lixo", address: "lixo", contact: 1231231)
    @user.id = adoption_params[:user_id]
    if !User.where(cc: params[:user_cc]).any?
      var = 1
      @user = User.create(cc: params[:user_cc], name: params[:user_name], address: params[:user_address], contact: params[:user_contact])
    else
      @user = User.where(cc: params[:user_cc]).first
      @user.update(cc: params[:user_cc], name: params[:user_name], address: params[:user_address], contact: params[:user_contact])
    end
    adoption_params[:user_id] = @user.id
    @adoption = Adoption.new(adoption_params)
    @adoption.user_id = @user.id
    respond_to do |format|
      if @adoption.save
        animal = Animal.find(@adoption.animal_id)
        animal.status = @adoption.adoption_type
        animal.save
        format.html { redirect_to @adoption, notice: "Adoption was successfully created." }
        format.json { render :show, status: :created, location: @adoption }
      else
        if var == 1
          User.destroy(@user.id)
        end
        format.html { render :new }
        format.json { render json: @adoption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adoptions/1
  # PATCH/PUT /adoptions/1.json
  def update
    respond_to do |format|
      if @adoption.update(adoption_params)
        animal = Animal.find(@adoption.animal_id)
        animal.status = @adoption.adoption_type
        animal.save
        format.html { redirect_to @adoption, notice: "Adoption was successfully updated." }
        format.json { render :show, status: :ok, location: @adoption }
      else
        format.html { render :edit }
        format.json { render json: @adoption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adoptions/1
  # DELETE /adoptions/1.json
  def destroy
    @adoption.destroy
    respond_to do |format|
      format.html { redirect_to adoptions_url, notice: "Adoption was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_adoption
    @adoption = Adoption.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def adoption_params
    params.require(:adoption).permit(:adoption_date, :adoption_type, :end_date, :user_id, :animal_id, :employee_id)
  end
end

app/helpers/adoptions_helper.rb
module AdoptionsHelper
end

app/views/adoptions/_all_adoptions.html.erb
<% model_class = Adoption %>
<div class="box-body table-responsive">
  <table id="list_datatable" class="display table table-bordered table-striped text-center">
    <thead>
    <tr>
      <th class="text-center"><%= model_class.human_attribute_name(:adoption_Code) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:adoption_date) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:adoption_type) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:animal) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:user) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:employee) %></th>
      <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @adoptions.each do |adoption| %>
        <tr>
          <td class="text-center"><%= link_to adoption.id, adoption_path(adoption) %></td>
          <td><%= pretty_datetime(adoption.adoption_date) %></td>
          <% if(adoption.adoption_type == 1) %>
              <td class="text-center">Permanent</td>
          <% else %>
              <td class="text-center">Temporary</td>
          <%end%>
          <td><%= adoption.animal.id %> - <%= adoption.animal.name%></td>
          <td><%= adoption.user.name %></td>
          <td><%= adoption.employee.name %></td>

          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_adoption_path(adoption), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")), adoption_path(adoption.id), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs
                  btn-danger' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/adoptions/_animal_list.html.erb
<div class="clearfix"></div>
<% if action_name == 'edit' %>
    <div id="animals">
      <input class="search form-control" placeholder="Search" />
      <br>
      <ul class="list list-unstyled top_profiles scroll-view">
        <% @animals.each do |animal| %>
            <li class="media event">
              <div class="media-body">
                <a class="title name" href="#"><%= animal.name %></a>
                <p class="code">
                  <strong>Code:&nbsp</strong>
                  <%= animal.id %>
                </p>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
<% else %>
    <div id="animals">
      <input class="search form-control" placeholder="Search" />
      <br>
      <ul class="list list-unstyled top_profiles scroll-view">
        <% @animals.each do |animal| %>
            <li class="media event">
              <div class="media-body" onclick="$('#animal_code').val('<%= animal.id %>');$('#animal_id').val('<%= animal.id %>');$('#animal_name').val('<%= animal.name %>');">
                <a class="title name" href="#"><%= animal.name %></a>
                <p class="code">
                  <strong>Code:&nbsp</strong>
                  <%= animal.id %>
                </p>
              </div>
            </li>
        <% end %>

      </ul>
    </div>
<% end %>

</ul>

app/views/adoptions/_form.html.erb
<div class="form-horizontal form-label-left input_mask">
  <%= form_for(@adoption) do |f| %>
      <% if @adoption.errors.any? %>
          <div id="error_explanation">
            <h2 class="text-red"><%= pluralize(@adoption.errors.count, "error") %> prohibited this adoption from being saved:</h2>
          </div>
      <% end %>
      <%= f.hidden_field :user_id, id: 'user_id' %>
      <% if action_name == 'edit' %>
          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <%= f.text_field_tag :user_cc, nil, class: "form-control has-feedback-left", id: 'user_cc', placeholder: 'ID/Passport', value:@adoption.user.cc, disabled: true%>
            <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <%= f.text_field_tag :user_name, nil, class: "form-control", id: 'user_name', placeholder: 'Full Name', value:@adoption.user.name, disabled: true%>
            <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <%= f.text_field_tag :user_address, nil, class: "form-control has-feedback-left", id: 'user_address', placeholder: 'Address', value:@adoption.user.address, disabled: true%>
            <span class="fa fa-home form-control-feedback left" aria-hidden="true"></span>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <%= f.text_field_tag :user_contact, nil, class: "form-control", id: 'user_contact', placeholder: 'Phone', value:@adoption.user.contact, disabled: true%>
            <span class="fa fa-phone form-control-feedback right" aria-hidden="true"></span>
          </div>

          <div class="x_title">
            <h2><br>Animal Information</h2>
            <div class="clearfix"></div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <%= f.text_field :animal_id, class: "form-control has-feedback-left", id: 'animal_id', placeholder: 'Animal Code', value:@adoption.animal.id, disabled: true%>
            <span class="fa fa-paw form-control-feedback left" aria-hidden="true"></span>
          </div>

          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <%= f.text_field_tag :animal_name, nil, class: "form-control", id: 'animal_name', placeholder: 'Animal Name', value: @adoption.animal.name, disabled: true%>
            <span class="fa fa-paw form-control-feedback right" aria-hidden="true"></span>
          </div>
      <% else %>

          <div class="field_with_errors">
          <% if @adoption.errors[:user_id].any? %>
              <label for="adoption_adoption_date" class=" text-red message"><%= @adoption.errors[:user_id].first %></label><br>
          <% end %>
            </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <%= f.text_field_tag :user_cc, nil, class: "form-control has-feedback-left", id: 'user_cc', placeholder: 'ID/Passport'%>
            <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <%= f.text_field_tag :user_name, nil, class: "form-control", id: 'user_name', placeholder: 'Full Name'%>
            <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <%= f.text_field_tag :user_address, nil, class: "form-control has-feedback-left", id: 'user_address', placeholder: 'Address'%>
            <span class="fa fa-home form-control-feedback left" aria-hidden="true"></span>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <%= f.text_field_tag :user_contact, nil, class: "form-control", id: 'user_contact', placeholder: 'Phone'%>
            <span class="fa fa-phone form-control-feedback right" aria-hidden="true"></span>
          </div>

          <div class="x_title">
            <h2><br>Animal Information <small> (Please select an animal from panel on the right)</small></h2>
            <div class="clearfix"></div>
          </div>

          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
            <div class="field_with_errors">

            <%= f.text_field_tag :animal_code, nil, class: "form-control has-feedback-left", id: 'animal_code', placeholder: 'Animal Code', disabled: true %>
            <%= f.hidden_field :animal_id, id: 'animal_id' %>
              <span class="fa fa-paw form-control-feedback left" aria-hidden="true"></span>

              <% if @adoption.errors[:animal_id].any? %>
                  <label for="adoption_adoption_date" class=" text-red message"><%= @adoption.errors[:animal_id].first %></label>
              <% end %>
          </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">

            <div class="field_with_errors">
            <%= f.text_field_tag :animal_name, nil, class: "form-control", id: 'animal_name', placeholder: 'Animal Name', disabled: true%>
            <span class="fa fa-paw form-control-feedback right" aria-hidden="true"></span>

              <% if @adoption.errors[:animal_id].any? %>
                  <label for="adoption_adoption_date" class=" text-red message"><%= @adoption.errors[:animal_id].first %></label>
              <% end %>
          </div>
          </div>
      <% end %>


      <div class="x_title">
        <h2><br>Adoption Information</h2>
        <div class="clearfix"></div>
      </div>
      <div class="form-group">
        <%= f.label :adoption_date, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
        <div class="col-md-6 col-sm-9 col-xs-12">
          <%= f.text_field :adoption_date,  {class: "form-control has-feedback-left col-md-7 col-xs-12", id: 'date_picker2'}%>
          <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :adoption_type, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
        <div class="col-md-6 col-sm-9 col-xs-12">
          <%= f.select :adoption_type, [['Permanent', 1], ['Temporary', 2]], {}, { class: "form-control col-md-7 col-xs-12"}%>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :employee_id, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
        <div class="col-md-6 col-sm-9 col-xs-12">
          <%= f.text_field :employee,  class: "form-control col-md-7 col-xs-12", disabled: true, value: current_employee.name%>
          <%= f.hidden_field :employee_id , value: current_employee.id%>
        </div>
      </div>
      <div class="ln_solid"></div>
      <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
          <div class="actions">
            <%= f.submit 'Submit', class:'btn btn-success'%>
            <%= link_to 'Back', adoptions_path , class:'btn btn-primary'%>
          </div>
        </div>
      </div>
  <% end %>

</div>

app/views/adoptions/_list.html.erb
<div>
  <div class="x_title">
    <h2 id="name_list">User List &nbsp&nbsp&nbsp<small class="pull-right" id="info_list">(Select one to automatically fill adopter information)</small></h2>

    <div class="clearfix"></div>
  </div>
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active" id="tab1">
      <a href="#adopters" aria-controls="adopters" role="tab" data-toggle="tab">Users</a>

    </li>
    <li role="presentation" id="tab2">
      <a href="#animals" aria-controls="animals" role="tab" data-toggle="tab">Animals</a>
    </li>
  </ul>

  <div class="tab-content" style="background-color: white;">
    <div role="tabpanel" class="tab-pane active " id="adopters"><%= render 'user_list'%></div>
    <div role="tabpanel" class="tab-pane" id="animals"><%= render 'animal_list'%></div>
  </div>

  </div>

app/views/adoptions/_permanent_adoptions.html.erb
<% model_class = Adoption %>
<div class="box-body table-responsive">
  <table id="list_datatable1" class="display table table-bordered table-striped text-center">
    <thead>
    <tr>
      <th class="text-center"><%= model_class.human_attribute_name(:adoption_Code) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:adoption_date) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:adoption_type) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:animal) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:user) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:employee) %></th>
      <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @permanent_adoptions.each do |adoption| %>
        <tr>
          <td class="text-center"><%= link_to adoption.id, adoption_path(adoption) %></td>
          <td><%= pretty_datetime(adoption.adoption_date) %></td>
          <% if(adoption.adoption_type == 1) %>
              <td class="text-center">Permanent</td>
          <% else %>
              <td class="text-center">Temporary</td>
          <%end%>
          <td><%= adoption.animal.id %> - <%= adoption.animal.name%></td>
          <td><%= adoption.user.name %></td>
          <td><%= adoption.employee.name %></td>

          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_adoption_path(adoption), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")), adoption_path(adoption.id), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs
                  btn-danger' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/adoptions/_temporary_adoptions.html.erb
<% model_class = Adoption %>
<div class="box-body table-responsive">
  <table id="list_datatable2" class="display table table-bordered table-striped text-center">
    <thead>
    <tr>
      <th class="text-center"><%= model_class.human_attribute_name(:adoption_Code) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:adoption_date) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:adoption_type) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:animal) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:user) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:employee) %></th>
      <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @temporary_adoptions.each do |adoption| %>
        <tr>
          <td class="text-center"><%= link_to adoption.id, adoption_path(adoption) %></td>
          <td><%= pretty_datetime(adoption.adoption_date) %></td>
          <% if(adoption.adoption_type == 1) %>
              <td class="text-center">Permanent</td>
          <% else %>
              <td class="text-center">Temporary</td>
          <%end%>
          <td><%= adoption.animal.id %> - <%= adoption.animal.name%></td>
          <td><%= adoption.user.name %></td>
          <td><%= adoption.employee.name %></td>

          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_adoption_path(adoption), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")), adoption_path(adoption.id), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs
                  btn-danger' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/adoptions/edit.html.erb
<div class="right_col" role="main">

  <div class="title-left">
    <h3>New Adoption</h3>
  </div>

  <div class="row">
    <div class="col-md-8 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Adopter Information</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <%= render 'form' %>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-xs-12">
      <div class="x_panel">
        <%= render 'list' %>
      </div>
    </div>
  </div>
</div>

app/views/adoptions/show.html.erb
<div class="right_col" role="main">

  <div class="row">
    <div class="col-md-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Adoption Information</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="col-md-11 col-md-offset-1">
            <ul class="list-unstyled">
              <li><h5 ><span class="fa fa-calendar-o" style="font-size:15px;" aria-hidden="true"></span>&nbsp&nbsp<strong >Date: </strong><%= pretty_datetime(@adoption.adoption_date) %></h5>
              </li>
              <li><h5><span class="fa fa-check" style="font-size:15px;" aria-hidden="true"></span>&nbsp&nbsp<strong>Adoption type:</strong> <% if(@adoption.adoption_type == 1) %>
                    Permanent
                <% else %>
                    Temporary
                <%end%></h5>
              </li>
              <div class="clearfix"></div>
              <li>
                <h5><span class="fa fa-paw" style="font-size:15px;" aria-hidden="true"></span>&nbsp&nbsp<strong>Animal:</strong> <%= @adoption.animal.name %></h5>
                <h5><span class="fa fa-lock" style="font-size:15px;" aria-hidden="true"></span>&nbsp&nbsp&nbsp<strong>Animal Code:</strong> <%= @adoption.animal.id %></h5>
              </li>
              <div class="clearfix"></div>
              <li>
                <h5><span class="fa fa-user" style="font-size:17px;" aria-hidden="true"></span>&nbsp&nbsp<strong>User:</strong> <%= @adoption.user.name %></h5>
                <h5><span class="fa fa-cc" style="font-size:15px;" aria-hidden="true"></span>&nbsp<strong>User CC:</strong> <%= @adoption.user.cc %></h5>
              </li>

              <div class="clearfix"></div>
              <li>
                <h5><span class="fa fa-user-plus" style="font-size:15px;" aria-hidden="true"></span> <strong>Employee:</strong> <%= @adoption.employee.name %></h5>
                <h5><span class="fa fa-lock" style="font-size:15px;" aria-hidden="true"></span>&nbsp&nbsp&nbsp<strong>Employee Code:</strong> <%= @adoption.employee.id %></h5>
              </li>
            </ul>

          </div>
            <div class="x_title">
              <div class="clearfix"></div>
              <br>
            </div>

          <div class="col-md-11 col-md-offset-1">
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <div class="actions">
                  <%= link_to 'Edit', edit_adoption_path(@adoption),  class:'btn btn-success'%>
                  <%= link_to 'Back', adoptions_path , class:'btn btn-primary'%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-xs-12">

        <div class="x_panel size-of-adoption-panel">

          <div class="x_title">
        <h2 id="name_list">Adoptions of this User</h2>
        <div class="clearfix"></div>
      </div>

          <div class="x_content">
      <ul class="list list-unstyled top_profiles scroll-view" role="tablist">
        <% if @previous_adoptions.size >0 %>
            <% @previous_adoptions.each do |adoption| %>
                <li>
                    <strong> Date:</strong> <%= adoption.adoption_date %>
                      <br>
                    <strong> Animal:</strong> <%= adoption.animal.name %>
                      <br>
                    <% if(adoption.adoption_type == 1) %>
                      <strong>Type:</strong> Permanent
                    <% else %>
                      <strong>Type:</strong> Temporary
                    <%end%>
                </li>
            <% end %>
        <%else%>
            <strong>This user has no other adoptions</strong>
        <%end%>
      </ul>

    </div>
    </div>
    </div>

  </div>
  </div>
</div>