config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/donations', as: :user_donation

  get 'static_pages/volunteer', as: :user_volunteer

  resources :animal_images
  get 'employees/list' => 'employees#list', as: :employees_list
  devise_for :employees, controllers: {sessions: "sessions", registrations: "employees"}
  resources :employees do
    collection do
      get 'animals' => 'animals#list', as: :animals_list
      get 'animals/new' => 'animals#new', as: :new_animal
      get 'animals/:id' => 'animals#show_employees', as: :show_animal
    end
  end
  get 'dogs' => 'animals#list_dogs', as: :animals_dogs
  get 'cats' => 'animals#list_cats', as: :animals_cats
  get 'animals/filters' => 'animals#filters', as: :animal_filters
  post  'requests/all'  =>            'requests#update_all', as: :update_all_request
  post  'requests/:id'  =>            'requests#update', as: :update_request
  get 'return_animal/:id' => 'animals#return', as: :return_animal_to_shelter
  get 'requests/new/:animal_id' => 'requests#new', as: :new_adoption_request

  get 'endanger/:id' => 'animals#endanger', as: :animal_in_danger
  get 'save/:id' => 'animals#save', as: :animal_save

  delete 'requests' => 'requests#destroy_all'
  get 'global_stats' => 'charts#global_stats', as: :global_stats
  get 'donations_stats' => 'donations#stats', as: :donations_stats

  resources :animals
  resources :requests, only: [:index, :new, :create,:destroy]
  resources :adoptions
  resources :shelter
  resources :donations
  resources :volunteers
  resources :emails, only: [:new, :create]

  get '/'                        => 'static_pages#index',         as: :user_index
  get '/about'                   => 'static_pages#about',         as: :about
  get '/contacts'                => 'static_pages#contacts',      as: :contacts
  get '/animals'                 => 'animals#user_index',         as: :animals_user_index

   root 'static_pages#index'

   match "*path" => "static_pages#index", via: [:get, :post]

end

app/models/animal.rb
include AnimalsHelper

class Animal < ActiveRecord::Base
  include ActionView::Helpers::AssetUrlHelper
  before_validation :set_status

  has_many :adoptions
  has_many :users, through: :adoptions
  belongs_to :breed

  has_many :animal_images
  accepts_nested_attributes_for :animal_images

  serialize :images, JSON

  scope :last_month_arrivals, -> {
    where("entry_date >= ? AND entry_date <= ?",
      Date.today.last_month.beginning_of_month.to_date,
      Date.today.last_month.end_of_month.to_date)
  }
  validates_presence_of :name, :date_of_birth, :size, :entry_date, :animal_type, :gender, :breed
  validate :entry_date_after_birth
  validate :entry_date_and_date_of_birth

  def endangered?
    endangered
  end

  def first_image_url
    if !animal_images.empty?
      animal_images.first.image.standard.url
    else
      asset_path("animal_placeholder.png")
    end
  end

  def self.amount_1_year_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      1.year.ago.beginning_of_month.to_date,
      1.year.ago.end_of_month.to_date).size
  end

  def self.amount_11_months_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      11.months.ago.beginning_of_month.to_date,
      11.months.ago.end_of_month.to_date).size
  end

  def self.amount_10_months_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      10.months.ago.beginning_of_month.to_date,
      10.months.ago.end_of_month.to_date).size
  end

  def self.amount_9_months_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      9.months.ago.beginning_of_month.to_date,
      9.months.ago.end_of_month.to_date).size
  end

  def self.amount_8_months_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      8.months.ago.beginning_of_month.to_date,
      8.months.ago.end_of_month.to_date).size
  end

  def self.amount_7_months_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      7.months.ago.beginning_of_month.to_date,
      7.months.ago.end_of_month.to_date).size
  end

  def self.amount_6_months_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      6.months.ago.beginning_of_month.to_date,
      6.months.ago.end_of_month.to_date).size
  end

  def self.amount_5_months_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      5.months.ago.beginning_of_month.to_date,
      5.months.ago.end_of_month.to_date).size
  end

  def self.amount_4_months_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      4.months.ago.beginning_of_month.to_date,
      4.months.ago.end_of_month.to_date).size
  end

  def self.amount_3_months_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      3.months.ago.beginning_of_month.to_date,
      3.months.ago.end_of_month.to_date).size
  end

  def self.amount_2_months_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      2.months.ago.beginning_of_month.to_date,
      2.months.ago.end_of_month.to_date).size
  end

  def self.amount_1_month_ago
    Animal.where("entry_date >= ? AND entry_date <= ?",
      1.month.ago.beginning_of_month.to_date,
      1.month.ago.end_of_month.to_date).size
  end

  def self.all_animals_filter
    Animal.where(status: [0, 1])
  end

  def self.filter_animal_by_type(type)
    if type == 0
      Animal.where(status: [0, 1])
    else
      Animal.where(animal_type: type, status: [0, 1])
    end
  end

  def self.filter_animals_by_size(size)
    Animal.where(size: size, status: [0, 1])
  end

  def self.filter_animals_by_breed(breed)
    Animal.where(breed: breed, status: [0, 1])
  end

  def self.filter_animals_by_age(age)
    case age
    when 0
      Animal.where("date_part('year', age(date_of_birth)) < 1").where(status: [0, 1])
    when 1
      Animal.where("date_part('year', age(date_of_birth)) >= 1 AND date_part('year', age(date_of_birth)) < 3").where(status: [0, 1])
    else
      Animal.where("date_part('year', age(date_of_birth)) >= 3").where(status: [0, 1])
    end
  end

  def self.prepare_response(animals)
    response = []
    animals.each do |animal|
      has_image = !animal.animal_images.empty?
      img_url = animal.first_image_url
      age = ""
      age_in_years = AnimalsHelper.age_in_years(animal.date_of_birth)
      if age_in_years == 0
        age_in_months = age_in_months(animal.date_of_birth)
        age = if age_in_months == 0
                "<= 1 Month"
              else
                age_in_months.to_s + " (Month)"
              end
      else
        age = age_in_years.to_s + " (Years)"
      end
      gender = if animal.gender == 0
                 "fa fa-venus girl-color"
               else
                 "fa fa-mars boy-color"
               end
      response.push('id': animal.id, 'name': animal.name, 'description': animal.description, 'has_image': has_image, 'img_url': img_url, 'age': age, 'gender': gender, 'danger': animal.endangered?)
    end
    response
  end

  private

  def set_status
    self.status ||= 0
  end

  def entry_date_after_birth
    if !entry_date.nil? && !date_of_birth.nil?
      if entry_date <= date_of_birth
        errors.add(:entry_date, "must be after animal's birth")
      end
    end
  end

  def entry_date_and_date_of_birth
    if !entry_date.nil? && !date_of_birth.nil?
      now = DateTime.now.to_date
      if now < date_of_birth
        errors.add(:date_of_birth, "cannot be in the future")
      elsif now < entry_date
        errors.add(:entry_date, "cannot be in the future")
      end
    end
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  include ApplicationHelper
  layout :select_layout
  before_action :set_breeds
  before_action :set_animal, only: [:show, :edit, :update, :destroy, :show_employees, :return, :endanger, :save]
  before_filter :custom_user_auth, only: [:edit, :update, :destroy, :show_employees, :create, :new, :list]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.where(status: [0, 1])
  end

  # GET /animals
  # GET /animals.json
  def list
    @animals = Animal.all
    @shelter_animals = Animal.where(status: 0)
    @adopted_animals = Animal.where(status: 2)
    @ff_animals = Animal.where(status: 1)
    render "animals/index_employees"
  end

  def list_dogs
    @animals = Animal.where(animal_type: 1, status: [0, 1])
    @dog_breeds = Breed.where(animal_type: 1)
    render "animals/index_dogs"
  end

  def list_cats
    @animals = Animal.where(animal_type: 2, status: [0, 1])
    @cat_breeds = Breed.where(animal_type: 2)
    render "animals/index_cats"
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  def show_employees
    render "animals/show_animal_employee"
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)
    @animal.breed_id = if animal_params[:animal_type] == "1"
                         params[:dog_breed_id]
                       else
                         params[:cat_breed_id]
                       end
    @animal.name.capitalize!
    respond_to do |format|
      if @animal.save
        if params[:animal_images]
          params[:animal_images][:image].each do |img|
            @animal_image = @animal.animal_images.create(image: img, animal: @animal)
          end
        end
        format.html { redirect_to show_animal_employees_path(@animal), notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    @breed = nil
    @breed = if animal_params[:animal_type] == "1"
               Breed.where(id: params[:dog_breed_id]).first
             else
               Breed.where(id: params[:cat_breed_id]).first
             end
    @animal.breed = @breed
    new_params = animal_params
    new_params[:breed_id] = @breed.id
    respond_to do |format|
      if @animal.update(new_params)
        if params[:animal_images]
          params[:animal_images][:image].each do |img|
            @animal_image = @animal.animal_images.create(image: img)
          end
        end
        format.html { redirect_to show_animal_employees_path(@animal), notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_list_employees_path, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def filter_by_breed(animals, breed_filter)
    if breed_filter != -1
      breed_animals =  Animal.filter_animals_by_breed(breed_filter).to_a
      return elements_in_both(breed_animals, animals)
    else
      return animals
    end
  end

  def filter_by_size(animals, size_filter)
    if size_filter != -1
      size_animals =  Animal.filter_animals_by_size(size_filter).to_a
      return elements_in_both(size_animals, animals)
    else
      return animals
    end
  end

  def filter_by_age(animals, age_filter)
    if age_filter != -1
      age_animals =  Animal.filter_animals_by_age(age_filter).to_a
      return elements_in_both(age_animals, animals)
    else
      return animals
    end
  end

  def set_breeds
    @breeds_cats = Breed.where(animal_type: 2)
    @breeds_dogs = Breed.where(animal_type: 1)
  end

  def filters
    breed_filter = params[:breed_filter].to_i
    size_filter = params[:size_filter].to_i
    age_filter = params[:age_filter].to_i
    type_filter = params[:animal_type_filter].to_i
    type_animals = Animal.filter_animal_by_type(type_filter).to_a
    animals = filter_by_breed(type_animals, breed_filter)
    animals = filter_by_size(animals, size_filter)
    animals = filter_by_age(animals, age_filter)
    final_response = Animal.prepare_response(animals)
    render json: final_response
  end

  def return
    @animal.status = 0
    @animal.save
    redirect_to :animals_list_employees
  end

  def endanger
    @animal.endangered = true
    @animal.save
    redirect_to :animals_list_employees
  end

  def save
    @animal.endangered = false
    @animal.save
    redirect_to :animals_list_employees
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :date_of_birth, :breed_id, :dog_breed_id, :cat_breed_id, :photo, :size, :gender,
      :description, :entry_date, :status, :medical_conditions,
      :animal_type, animal_images_attributes: [:id, :animal_id, :image, :remove_image])
  end

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def select_layout
    case action_name
    when "index", "show", "list_cats", "list_dogs"
      "users"
    else
      "employees"
    end
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
  def age_in_years(birthday)
    now = Time.now.utc.to_date
    now.year - birthday.year - (birthday.to_date.change(year: now.year) > now ? 1 : 0)
  end

  def age_in_months(birthday)
    now = Time.now.utc.to_date
    difference_in_days = now - birthday
    (difference_in_days / 30).round
  end
end

app/views/animals/_ff_animals.html.erb
<% model_class = Animal %>
<div class="box-body table-responsive">
  <table id="list_datatable1" class="display table table-bordered table-striped text-center">
    <thead>
    <tr>
      <th class="text-center"><%= model_class.human_attribute_name(:animal_Code) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:name) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:animal_type) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:breed) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:size) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:gender) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:date_of_birth) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:status) %></th>
      <th class="text-center"><%= model_class.human_attribute_name(:entry_date) %></th>
      <th class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @ff_animals.each do |animal| %>
        <tr>
          <td class="text-center"><%= link_to animal.id, show_animal_employees_path(animal) %></td>
          <td><%= animal.name %></td>
          <% if(animal.animal_type == 1) %>
              <td class="text-center">Dog</td>
          <% else %>
              <td class="text-center">Cat</td>
          <%end%>
          <td><%= animal.breed.name %></td>
          <td>
            <% case animal.size %>
            <% when 0%>
                <%= 'Mini'%>
            <% when 1%>
                <%= 'Small'%>
            <% when 2%>
                <%= 'Medium'%>
            <% when 3%>
                <%= 'Large'%>
            <% else %>
                <%= 'Giant'%>
            <% end %>
          </td>
          <td>
            <% case animal.gender %>
            <% when 0%>
                <%= 'Female'%>
            <% else %>
                <%= 'Male'%>
            <% end %>
          </td>
          <td><%= pretty_date(animal.date_of_birth) %>

          <td>
            <% case animal.status %>
            <% when 0%>
                <%= 'In Shelter'%>
            <% when 1 %>
                <%= 'With FF'%>
            <% else %>
                <%= 'Adopted'%>
            <% end %></td>
          <td><%= pretty_date(animal.entry_date) %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_animal_path(animal), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")), animal_path(animal.id), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs
                  btn-danger' %>
            <% if animal.status == 1 %>
                <%= link_to 'Return', return_animal_to_shelter_path(animal), :class => 'btn btn-primary btn-xs' %>
            <% end %>
            <% if animal.endangered? %>
              <%= link_to 'Safe', animal_save_path(animal), :class => 'btn btn-info btn-xs' %>
            <% else %>
              <%= link_to 'Danger', animal_in_danger_path(animal), :class => 'btn btn-warning btn-xs' %>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/animals/_shelter_animals.html.erb
<% model_class = Animal %>
<div class="box-body table-responsive">
  <table id="list_datatable" class="display table table-bordered table-striped text-center">
    <thead>
    <tr>
      <th  class="text-center"><%= model_class.human_attribute_name(:animal_Code) %></th>
      <th  class="text-center"><%= model_class.human_attribute_name(:name) %></th>
      <th  class="text-center"><%= model_class.human_attribute_name(:animal_type) %></th>
      <th  class="text-center"><%= model_class.human_attribute_name(:breed) %></th>
      <th  class="text-center"><%= model_class.human_attribute_name(:size) %></th>
      <th  class="text-center"><%= model_class.human_attribute_name(:gender) %></th>
      <th  class="text-center"><%= model_class.human_attribute_name(:date_of_birth) %></th>
      <th  class="text-center"><%= model_class.human_attribute_name(:status) %></th>
      <th  class="text-center"><%= model_class.human_attribute_name(:entry_date) %></th>
      <th  class="text-center"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @shelter_animals.each do |animal| %>
        <tr>
          <td class="text-center"><%= link_to animal.id, show_animal_employees_path(animal) %></td>
          <td><%= animal.name %></td>
          <% if(animal.animal_type == 1) %>
              <td class="text-center">Dog</td>
          <% else %>
              <td class="text-center">Cat</td>
          <%end%>
          <td><%= animal.breed.name %></td>
          <td>
            <% case animal.size %>
            <% when 0%>
                <%= 'Mini'%>
            <% when 1%>
                <%= 'Small'%>
            <% when 2%>
                <%= 'Medium'%>
            <% when 3%>
                <%= 'Large'%>
            <% else %>
                <%= 'Giant'%>
            <% end %>
          </td>
          <td>
            <% case animal.gender %>
            <% when 0%>
                <%= 'Female'%>
            <% else %>
                <%= 'Male'%>
            <% end %>
          </td>
          <td><%= pretty_date(animal.date_of_birth) %>

          <td>
            <% case animal.status %>
            <% when 0%>
                <%= 'In Shelter'%>
            <% when 1 %>
                <%= 'With FF'%>
            <% else %>
                <%= 'Adopted'%>
            <% end %></td>
          <td><%= pretty_date(animal.entry_date) %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_animal_path(animal), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")), animal_path(animal.id), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs
                  btn-danger' %>
            <% if animal.status == 1 %>
                <%= link_to 'Return', return_animal_to_shelter_path(animal), :class => 'btn btn-primary btn-xs' %>
            <% end %>
            <% if animal.endangered? %>
              <%= link_to 'Safe', animal_save_path(animal), :class => 'btn btn-info btn-xs' %>
            <% else %>
              <%= link_to 'Danger', animal_in_danger_path(animal), :class => 'btn btn-warning btn-xs' %>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/animals/edit.html.erb
<div class="right_col" role="main">

  <div class="title-left">
    <h3>Edit Animal</h3>
  </div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2> Animal Information</h2>

          <div class="clearfix"></div>
        </div>

        <div class="x_content">
          <br>

          <div class="form-horizontal form-label-left">

            <%= render 'form' %>

          </div>

        </div>

      </div>
    </div>
  </div>
</div>

app/views/animals/index.html.erb
<div class="container">
  <h2 class="page-header">Adopt a Friend
    <%= image_tag '/assets/images/icon1.png' %></h2>

  <div class="row">
    <div class="col-md-3" style="margin-bottom: 8px;">
      <%= link_to 'All', animals_path, :class => 'btn btn-primary' %>
      <%= link_to 'Cats', animals_cats_path, :class => 'btn btn-default' %>
      <%= link_to 'Dogs', animals_dogs_path, :class => 'btn btn-default' %>
    </div>
    <div id="animal_filters" class="col-md-6 col-md-offset-3">
      <div class="input-group pull-right">
        <select id="breed_filters" class="form-control selectWidth hidden">
          <option value="-1" selected>- Breed -</option>
        </select>
        <select id="animal_type_filters" class="form-control selectWidth hidden">
          <option value="0" selected>All</option>
        </select>
        <select id="size_filters" class="form-control selectWidth">
          <option value="-1" selected>- Size -</option>
          <option value="0">Mini</option>
          <option value="1">Small</option>
          <option value="2">Medium</option>
          <option value="3">Large</option>
          <option value="4">Giant</option>
        </select>
        <select id="age_filters" class="form-control selectWidth">
          <option value="-1" selected>- Age -</option>
          <option value="0">Puppy</option>
          <option value="1">Junior</option>
          <option value="2">Adult</option>
        </select>
        &nbsp
        <button id="the_cleaner" class="btn btn-primary">Clean</button>
      </div>
    </div>
  </div>

  <br>
  <div class="row" id="animals_list">
    <% if @animals.size > 0 %>
    <% @animals.each do |animal| %>
    <div class="col-md-3 portfolio-item">
      <div class="panel panel-default my_panel">
        <div class="panel-body">
          <% if animal.animal_images.size > 0 %>
          <%= link_to image_tag(animal.animal_images.first.image.standard.url, class: 'img-responsive'), animal_path(animal) %>
        <% else %>
          <%= link_to image_tag('/assets/images/animal_placeholder.png', class: 'img-responsive'), animal_path(animal) %>
          <% end %>
        </div>
        <div class="panel-footer without-padding">
          <h4 class="without-margin">
            <%= animal.name %>
            <% if animal.endangered? %>
            <span class="fa fa-exclamation-circle text-danger" aria-hidden="true" title="This animal is in DANGER!"></span>
            <% end %>
          </h4>
          <p class="without-margin">
            <small>Age:
              <% age_in_years = age_in_years(animal.date_of_birth) %>
              <% if age_in_years == 0 %>
              <% age_in_months = age_in_months(animal.date_of_birth) %>
              <% if  age_in_months == 0%>
              <%= '< 1 Month' %>
            <% else %>
              <%= age_in_months.to_s + ' (Month)' %>
              <% end %>
            <% else %>
              <%= age_in_years.to_s + ' (Years)'%>
              <% end %></small>
          </p>
          <p class="without-margin">
            <small>Gender:
              <% if animal.gender == 0%>
              <span class="fa fa-venus girl-color" aria-hidden="true"></span>
              <%else%>
              <span class="fa fa-mars boy-color" aria-hidden="true"></span>
              <% end%>
            </small>
          </p>
        </div>
      </div>
    </div>

    <% end %>
  <% else %>
    <div class="jumbotron">
      <h1 class="text-center">NO ANIMALS</h1>
    </div>
  <% end %>
  </div>
</div>
<!-- /.container -->

app/views/animals/index_cats.html.erb
<div class="container">
  <h2 class="page-header">Adopt a Friend <%= image_tag '/assets/images/icon1.png' %></h2>

  <div class="row">
    <div class="col-md-3" style="margin-bottom: 8px;">
      <%= link_to 'All', animals_path, :class => 'btn btn-default' %>
      <%= link_to 'Cats', animals_cats_path, :class => 'btn btn-primary' %>
      <%= link_to 'Dogs', animals_dogs_path, :class => 'btn btn-default' %>
    </div>
    <div id="animal_filters" class="col-md-6 col-md-offset-3">
      <div class="input-group pull-right">
        <select id="animal_type_filters" class="form-control selectWidth hidden">
          <option value="2" selected>Cat</option>
        </select>
        <select id="breed_filters" class="form-control selectWidth">
          <option value="-1" selected>- Breed -</option>
          <% @cat_breeds.each do |breed| %>
              <option value="<%= breed.id %>"><%= breed.name %></option>
          <% end %>
        </select>
        <select id="size_filters" class="form-control selectWidth">
          <option value="-1" selected>- Size -</option>
          <option value="0">Mini</option>
          <option value="1">Small</option>
          <option value="2">Medium</option>
          <option value="3">Large</option>
          <option value="4">Giant</option>
        </select>
        <select id="age_filters" class="form-control selectWidth">
          <option value="-1" selected>- Age -</option>
          <option value="0">Puppy</option>
          <option value="1">Junior</option>
          <option value="2">Adult</option>
        </select>
        &nbsp
        <button id="the_cleaner" class="btn btn-primary">Clean</button>
      </div>
    </div>
  </div>

  <br>
  <div class="row" id="animals_list">
    <% if @animals.size > 0 %>
    <% @animals.each do |animal| %>
    <div class="col-md-3 portfolio-item">
      <div class="panel panel-default my_panel">
        <div class="panel-body">
          <% if animal.animal_images.size > 0 %>
          <%= link_to image_tag(animal.animal_images.first.image.standard.url, class: 'img-responsive'), animal_path(animal) %>
        <% else %>
          <%= link_to image_tag('animal_placeholder.png', class: 'img-responsive'), animal_path(animal) %>
          <% end %>
        </div>
        <div class="panel-footer without-padding">
          <h4 class="without-margin">
            <%= animal.name %>
            <% if animal.endangered? %>
            <span class="fa fa-exclamation-circle text-danger" aria-hidden="true" title="This animal is in DANGER!"></span>
            <% end %>
          </h4>
          <p class="without-margin">
            <small>Age:
              <% age_in_years = age_in_years(animal.date_of_birth) %>
              <% if age_in_years == 0 %>
              <% age_in_months = age_in_months(animal.date_of_birth) %>
              <% if  age_in_months == 0%>
              <%= '< 1 Month' %>
            <% else %>
              <%= age_in_months.to_s + ' (Month)' %>
              <% end %>
            <% else %>
              <%= age_in_years.to_s + ' (Years)'%>
              <% end %></small>
          </p>
          <p class="without-margin">
            <small>Gender:
              <% if animal.gender == 0%>
              <span class="fa fa-venus girl-color" aria-hidden="true"></span>
              <%else%>
              <span class="fa fa-mars boy-color" aria-hidden="true"></span>
              <% end%>
            </small>
          </p>
        </div>
      </div>
    </div>

    <% end %>
  <% else %>
    <div class="jumbotron">
      <h1 class="text-center">NO CATS</h1>
    </div>
  <% end %>
  </div>
</div>
</div>

app/views/animals/new.html.erb
<div class="right_col" role="main">

  <div class="title-left">
    <h3>New Animal</h3>
  </div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2> Animal Information</h2>

          <div class="clearfix"></div>
        </div>

        <div class="x_content">
          <br>

          <div class="form-horizontal form-label-left">

            <%= render 'form' %>

          </div>

        </div>

      </div>
    </div>
  </div>
</div>